name = "shopping-bird"
main = "src/worker.ts"
compatibility_date = "2025-06-15"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "SHOPPING_LIST"
class_name = "ShoppingListDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ShoppingListDurableObject"]

[env.production]
name = "shopping-bird"

[env.preview]
name = "shopping-bird-preview"

[vars]
ENVIRONMENT = "development"