name = "shopping-bird"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[durable_objects.bindings]]
name = "SHOPPING_LIST"
class_name = "ShoppingListDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ShoppingListDurableObject"]

[vars]
ENVIRONMENT = "development"